<?xml version="1.0" encoding="utf-8"?><Database Name="OOP" Class="Shop_DBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=34.176.57.189;Initial Catalog=OOP;Persist Security Info=True;User ID=sqlserver;Trust Server Certificate=True" SettingsObjectName="Coffee_Shop_Management_System.Properties.Settings" SettingsPropertyName="OOPConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ACCOUNTS" Member="ACCOUNTs">
    <Type Name="ACCOUNT">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.Data.Linq.Binary" DbType="VarBinary(256) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Role" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.History" Member="Histories">
    <Type Name="History">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Customer_name" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="Price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Feed_back" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.Inventory" Member="Inventories">
    <Type Name="Inventory">
      <Column Name="coffee" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="condensed_milk" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fresh_milk" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[table]" Member="table" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="chair" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Coffes" Member="Coffes">
    <Type Name="Coffe">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>